#!/bin/bash

#SBATCH --job-name=d2q9-bgk
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=144
#SBATCH --time=00:30:00
#SBATCH --output=d2q9-bgk.out
#SBATCH --exclusive 

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

make clean
make

CPU_COUNTS=(1 16 32 64 128 144)
#CPU_COUNTS=(1 128)
run_case () {
    GRID=$1

    for CPUS in "${CPU_COUNTS[@]}"
    do
        echo "======================================="
        echo "Running ${GRID} with ${CPUS} threads"
        echo "======================================="

        export OMP_NUM_THREADS=$CPUS
        export OMP_PROC_BIND=true
        export OMP_PLACES=cores

        ./d2q9-bgk input_${GRID}.params obstacles_${GRID}.dat

        make check \
        REF_AV_VELS_FILE=check/${GRID}.av_vels.dat \
        REF_FINAL_STATE_FILE=check/${GRID}.final_state.dat
    done
}

run_case 128x128
run_case 128x256
run_case 256x256
run_case 1024x1024

